name: first-workflow

on: 
  push: 
    branches: ["main"]

jobs:
  job1: 
    runs-on: ubuntu-latest
    steps:
      - name: Running Single Command in Job1
        run: echo "Hi this is my first GitHub Workflow"
      - name: Checking os release for my Hosted Runner
        run: cat /etc/os-release

    
